version: '3.7'
services:
  app:
    build:
      context: .
      target: test
    ports:
      - 5000:5000
    command: go run .
    depends_on:
      - mongo
    volumes:
      - '.:/go/src/github.com/AngelVlc/lists-backend'
    env_file: 
      - ./local.env
    init: true

  mongo:
    image: mongo
    init: true
